[workspace]
resolver = "2"

members = [
    "contracts/admin",
    "contracts/lifecycle",
    "contracts/rate-limit",
    "contracts/split",
    "contracts/token",
    "contracts/ttl",
    "contracts/vesting",
    "contracts/wrapper",
    "e2e"
]
default-members = [
    "contracts/admin",
    "contracts/lifecycle",
    "contracts/rate-limit",
    "contracts/split",
    "contracts/token",
    "contracts/ttl",
    "contracts/vesting",
    "contracts/wrapper"
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
