import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import type { AddressInfo } from 'node:net';
import apiRouter, { createApiRouter, jsonErrorHandler } from './api';
import { publishIndexerEvent } from './events';
import { setPrismaClientFactoryForTests } from './lib/prisma';

const API_TOKEN = 'test-indexer-api-token';
process.env.INDEXER_API_TOKEN = API_TOKEN;

// Use the default limiter settings so the rate-limit assertions below are
// deterministic regardless of the ambient environment.
delete process.env.INDEXER_RATE_LIMIT_MAX;
delete process.env.INDEXER_RATE_LIMIT_WINDOW_MS;

type Row = {
  id: string;
  createdAt: Date;
  [key: string]: unknown;
};

type FindManyArgs = {
  take?: number;
  skip?: number;
  cursor?: { id: string };
  orderBy?: unknown;
  where?: Record<string, unknown>;
};

function sortRows(rows: Row[]): Row[] {
  return [...rows].sort((a, b) => {
    const timeDiff = b.createdAt.getTime() - a.createdAt.getTime();
    if (timeDiff !== 0) {
      return timeDiff;
    }
    if (a.id === b.id) {
      return 0;
    }
    // id DESC tie-break so pages are stable when createdAt collides.
    return a.id < b.id ? 1 : -1;
  });
}

/**
 * In-memory Prisma `findMany` stub that honours the cursor pagination
 * arguments the API passes (`take`, `skip`, `cursor`, `orderBy`).
 */
/**
 * Apply a flat `where` filter object to an in-memory row array.
 *
 * Supports the subset of Prisma filter shapes generated by the API:
 *   { field: value }          — equality
 *   { field: { gte: n } }     — numeric >=
 *   { OR: [...] }             — at least one sub-filter matches
 *   { AND: [...] }            — all sub-filters match
 */
function applyWhere(rows: Row[], where: Record<string, unknown> | undefined): Row[] {
  if (!where) return rows;

  function matchesFilter(row: Row, filter: Record<string, unknown>): boolean {
    if ('AND' in filter) {
      return (filter.AND as Record<string, unknown>[]).every((f) => matchesFilter(row, f));
    }
    if ('OR' in filter) {
      return (filter.OR as Record<string, unknown>[]).some((f) => matchesFilter(row, f));
    }
    return Object.entries(filter).every(([key, condition]) => {
      if (typeof condition === 'object' && condition !== null && 'gte' in condition) {
        return (row[key] as number) >= (condition as { gte: number }).gte;
      }
      return row[key] === condition;
    });
  }

  return rows.filter((row) => matchesFilter(row, where));
}

function createListMock(seed: Row[], seenArgs?: FindManyArgs[]) {
  return async (args: FindManyArgs = {}) => {
    seenArgs?.push(args);
    const filtered = applyWhere(seed, args.where);
    const sorted = sortRows(filtered);
    let start = 0;
    if (args.cursor) {
      const index = sorted.findIndex((row) => row.id === args.cursor?.id);
      if (index === -1) {
        const err = Object.assign(
          new Error(
            'An operation failed because it depends on one or more records that were required but not found.',
          ),
          { code: 'P2025' },
        );
        throw err;
      }
      start = index + (args.skip ?? 0);
    } else if (args.skip) {
      start = args.skip;
    }
    const take = args.take ?? sorted.length;
    return sorted.slice(start, start + take);
  };
}

function useMockLists(options: {
  mints?: Row[];
  transfers?: Row[];
  burns?: Row[];
  holders?: Row[];
  supplyPoints?: Row[];
  seenMintsArgs?: FindManyArgs[];
  seenTransfersArgs?: FindManyArgs[];
  seenBurnsArgs?: FindManyArgs[];
  seenHoldersArgs?: FindManyArgs[];
  seenSupplyPointsArgs?: FindManyArgs[];
}): void {
  const mints = options.mints ?? [];
  const transfers = options.transfers ?? [];
  const burns = options.burns ?? [];
  const holders = options.holders ?? [];
  const supplyPoints = options.supplyPoints ?? [];
  setPrismaClientFactoryForTests(
    () =>
      ({
        mint: {
          findMany: createListMock(mints, options.seenMintsArgs),
          count: async () => mints.length,
        },
        transfer: {
          findMany: createListMock(transfers, options.seenTransfersArgs),
          count: async () => transfers.length,
        },
        burn: {
          findMany: createListMock(burns, options.seenBurnsArgs),
          count: async () => burns.length,
        },
        holder: {
          findMany: createListMock(holders, options.seenHoldersArgs),
        },
        supplyPoint: {
          findMany: createListMock(supplyPoints, options.seenSupplyPointsArgs),
        },
        webhook: {
          findMany: async () => [],
        },
      }) as never,
  );
}

function makeRows(count: number, prefix: string, sameTimestamp = false): Row[] {
  const base = Date.UTC(2026, 0, 1);
  return Array.from({ length: count }, (_, i) => ({
    id: `${prefix}-${String(i).padStart(4, '0')}`,
    createdAt: new Date(sameTimestamp ? base : base + i * 1000),
    amount: '100',
  }));
}

const readRoutes = [
  '/api/v1/mints',
  '/api/v1/transfers',
  '/api/v1/burns',
  '/api/v1/holders',
  '/api/v1/supply-history',
  '/api/v1/stats',
];

/**
 * Boots a throwaway app that mirrors `index.ts`: the API router mounted at
 * `/api/v1`, an unauthenticated `/health` probe, and the shared JSON error
 * handler. Pass a fresh `createApiRouter()` to give a rate-limit test its own
 * in-memory store so counters do not leak between tests.
 */
async function withServer<T>(
  run: (baseUrl: string) => Promise<T>,
  router = apiRouter,
): Promise<T> {
  const app = express();
  app.use(express.json());
  app.use('/api/v1', router);
  app.get('/health', (req, res) => {
    res.json({ status: 'ok' });
  });
  // Same position as in index.ts: after all routes.
  app.use(jsonErrorHandler);

  const server = app.listen(0);
  await new Promise<void>((resolve) => server.once('listening', resolve));
  const { port } = server.address() as AddressInfo;

  try {
    return await run(`http://127.0.0.1:${port}`);
  } finally {
    await new Promise<void>((resolve, reject) => {
      server.close((err) => (err ? reject(err) : resolve()));
    });
  }
}

function authHeaders(): Record<string, string> {
  return { authorization: `Bearer ${API_TOKEN}` };
}

test('webhook registration accepts HTTPS targets and deletion removes the saved row', async () => {
  const saved = {
    id: 'hook-1',
    url: 'https://hooks.example.test/events',
    createdAt: new Date(Date.UTC(2026, 8, 27)),
  };
  const operations: string[] = [];

  setPrismaClientFactoryForTests(
    () =>
      ({
        webhook: {
          upsert: async (args: {
            where: { url: string };
            create: { url: string };
          }) => {
            operations.push(`upsert:${args.where.url}`);
            assert.equal(args.where.url, saved.url);
            assert.equal(args.create.url, saved.url);
            return saved;
          },
          delete: async (args: { where: { id: string } }) => {
            operations.push(`delete:${args.where.id}`);
            assert.equal(args.where.id, saved.id);
            return saved;
          },
          findMany: async () => [],
        },
      }) as never,
  );

  await withServer(async (baseUrl) => {
    const create = await fetch(`${baseUrl}/api/v1/webhooks`, {
      method: 'POST',
      headers: {
        ...authHeaders(),
        'content-type': 'application/json',
      },
      body: JSON.stringify({ url: saved.url }),
    });
    assert.equal(create.status, 201);
    assert.deepEqual(await create.json(), {
      data: JSON.parse(JSON.stringify(saved)),
    });

    const remove = await fetch(`${baseUrl}/api/v1/webhooks/${saved.id}`, {
      method: 'DELETE',
      headers: authHeaders(),
    });
    assert.equal(remove.status, 204);
    assert.equal(await remove.text(), '');
  });

  assert.deepEqual(operations, [`upsert:${saved.url}`, `delete:${saved.id}`]);
}, createApiRouter());

test('webhook registration rejects non-HTTPS targets', async () => {
  setPrismaClientFactoryForTests(
    () =>
      ({
        webhook: {
          upsert: async () => {
            throw new Error('upsert must not run for invalid URL');
          },
          findMany: async () => [],
        },
      }) as never,
  );

  await withServer(async (baseUrl) => {
    for (const url of ['http://example.test/hook', 'not-a-url', 'https://user:pw@example.test/hook']) {
      const res = await fetch(`${baseUrl}/api/v1/webhooks`, {
        method: 'POST',
        headers: {
          ...authHeaders(),
          'content-type': 'application/json',
        },
        body: JSON.stringify({ url }),
      });
      assert.equal(res.status, 400, url);
    }
  }, createApiRouter());
});

test('SSE stream emits one newly published indexer event', async () => {
  useMockLists({});

  await withServer(async (baseUrl) => {
    const response = await fetch(`${baseUrl}/api/v1/events/stream`, {
      headers: authHeaders(),
    });
    assert.equal(response.status, 200);
    assert.match(response.headers.get('content-type') ?? '', /^text\/event-stream/);
    assert.ok(response.body);

    const reader = response.body.getReader();
    const decoder = new TextDecoder();

    // Consume the initial ": connected" comment before publishing.
    const first = await reader.read();
    assert.equal(first.done, false);
    assert.match(decoder.decode(first.value), /connected/);

    const event = {
      type: 'mint' as const,
      data: { id: 'mint-live-1', to: 'GABC', amount: '5', ledger: 999 },
    };
    publishIndexerEvent(event);

    let payload = '';
    for (let i = 0; i < 4 && !payload.includes('mint-live-1'); i += 1) {
      const chunk = await reader.read();
      if (chunk.done) break;
      payload += decoder.decode(chunk.value, { stream: true });
    }

    assert.match(payload, /event: mint/);
    assert.match(payload, /mint-live-1/);
    assert.match(payload, /"ledger":999/);

    await reader.cancel();
  }, createApiRouter());
});

test('read routes return 401 without a bearer token', async () => {
  useMockLists({});
  await withServer(async (baseUrl) => {
    for (const route of readRoutes) {
      const res = await fetch(`${baseUrl}${route}`);
      assert.equal(res.status, 401, `${route} should require authentication`);
      assert.deepEqual(await res.json(), { error: 'Unauthorized' });
    }
  });
});

test('read routes return 401 with an invalid bearer token', async () => {
  useMockLists({});
  await withServer(async (baseUrl) => {
    const res = await fetch(`${baseUrl}/api/v1/mints`, {
      headers: { authorization: 'Bearer not-the-configured-token' },
    });
    assert.equal(res.status, 401);
  });
});

test('small lists return { data, nextCursor: null } and stats is unchanged', async () => {
  const mintRows: Row[] = [{ id: 'mint-1', to: 'GABC', amount: '100', createdAt: new Date() }];
  const transferRows: Row[] = [
    { id: 'transfer-1', from: 'GABC', to: 'GDEF', amount: '50', createdAt: new Date() },
  ];
  const burnRows: Row[] = [{ id: 'burn-1', from: 'GDEF', amount: '25', createdAt: new Date() }];
  useMockLists({ mints: mintRows, transfers: transferRows, burns: burnRows });

  await withServer(async (baseUrl) => {
    const mints = await fetch(`${baseUrl}/api/v1/mints`, { headers: authHeaders() });
    assert.equal(mints.status, 200);
    assert.deepEqual(await mints.json(), {
      data: JSON.parse(JSON.stringify(mintRows)),
      nextCursor: null,
    });

    const transfers = await fetch(`${baseUrl}/api/v1/transfers`, { headers: authHeaders() });
    assert.equal(transfers.status, 200);
    assert.deepEqual(await transfers.json(), {
      data: JSON.parse(JSON.stringify(transferRows)),
      nextCursor: null,
    });

    const burns = await fetch(`${baseUrl}/api/v1/burns`, { headers: authHeaders() });
    assert.equal(burns.status, 200);
    assert.deepEqual(await burns.json(), {
      data: JSON.parse(JSON.stringify(burnRows)),
      nextCursor: null,
    });

    const stats = await fetch(`${baseUrl}/api/v1/stats`, { headers: authHeaders() });
    assert.equal(stats.status, 200);
    assert.deepEqual(await stats.json(), {
      mintCount: mintRows.length,
      transferCount: transferRows.length,
      burnCount: burnRows.length,
    });
  });
});

test('a throwing handler returns 500 with a JSON body and logs one JSON line', async () => {
  setPrismaClientFactoryForTests(
    () =>
      ({
        mint: {
          findMany: async () => {
            throw new Error('boom');
          },
          count: async () => 0,
        },
        transfer: { findMany: async () => [], count: async () => 0 },
        burn: { findMany: async () => [], count: async () => 0 },
      }) as never,
  );

  const chunks: string[] = [];
  const originalWrite = process.stdout.write.bind(process.stdout);
  process.stdout.write = ((chunk: unknown, ...args: unknown[]) => {
    chunks.push(String(chunk));
    return (originalWrite as (...a: unknown[]) => boolean)(chunk, ...args);
  }) as typeof process.stdout.write;

  try {
    await withServer(async (baseUrl) => {
      const res = await fetch(`${baseUrl}/api/v1/mints`, {
        headers: { authorization: `Bearer ${API_TOKEN}` },
      });
      assert.equal(res.status, 500);
      const body = (await res.json()) as Record<string, unknown>;
      assert.deepEqual(body, { error: 'internal_error' });
      assert.ok(!JSON.stringify(body).includes('boom'), 'stack/message must not leak to client');
    });
  } finally {
    process.stdout.write = originalWrite;
  }

  // node --test TAP progress (and any harness framing bytes) share stdout;
  // only lines that parse as structured log records come from the logger.
  const lines = chunks
    .flatMap((chunk) => chunk.split('\n'))
    .filter((line) => {
      if (!line.startsWith('{')) {
        return false;
      }
      try {
        const parsed = JSON.parse(line) as Record<string, unknown>;
        return typeof parsed.level === 'string' && typeof parsed.message === 'string';
      } catch {
        return false;
      }
    });
  assert.equal(lines.length, 1, 'request failure should log exactly one JSON line');
  const logged = JSON.parse(lines[0]) as Record<string, unknown>;
  assert.equal(logged.level, 'error');
  assert.equal(logged.method, 'GET');
  assert.equal(logged.path, '/api/v1/mints');
  assert.ok(typeof logged.time === 'string');
  assert.ok(!JSON.stringify(logged).includes(API_TOKEN), 'logs must omit bearer tokens');
  assert.ok(
    !JSON.stringify(logged).includes('DATABASE_URL'),
    'logs must omit database URLs',
  );

  useMockLists({});
});

test('a non-Error rejection still returns 500 JSON with one scrubbed log line', async () => {
  setPrismaClientFactoryForTests(
    () =>
      ({
        mint: {
          // Non-Error rejection carrying secrets in the value.
          findMany: async () => {
            throw 'connection failed: postgresql://user:pw@host/db with Bearer abc-def-123';
          },
          count: async () => 0,
        },
        transfer: { findMany: async () => [], count: async () => 0 },
        burn: { findMany: async () => [], count: async () => 0 },
      }) as never,
  );

  const chunks: string[] = [];
  const originalWrite = process.stdout.write.bind(process.stdout);
  process.stdout.write = ((chunk: unknown, ...args: unknown[]) => {
    chunks.push(String(chunk));
    return (originalWrite as (...a: unknown[]) => boolean)(chunk, ...args);
  }) as typeof process.stdout.write;

  try {
    await withServer(async (baseUrl) => {
      const res = await fetch(`${baseUrl}/api/v1/mints`, {
        headers: { authorization: `Bearer ${API_TOKEN}` },
      });
      assert.equal(res.status, 500);
      assert.deepEqual(await res.json(), { error: 'internal_error' });
    });
  } finally {
    process.stdout.write = originalWrite;
  }

  const lines = chunks
    .flatMap((chunk) => chunk.split('\n'))
    .filter((line) => {
      if (!line.startsWith('{')) {
        return false;
      }
      try {
        const parsed = JSON.parse(line) as Record<string, unknown>;
        return typeof parsed.level === 'string' && typeof parsed.message === 'string';
      } catch {
        return false;
      }
    });
  assert.equal(lines.length, 1, 'non-Error failure should log exactly one JSON line');
  const serialized = lines[0];
  assert.ok(!serialized.includes('pw@host'), 'connection string must not be logged');
  assert.ok(!serialized.includes('abc-def-123'), 'bearer token must not be logged');
  assert.ok(!serialized.includes(API_TOKEN), 'request bearer token must not be logged');
  const logged = JSON.parse(serialized) as Record<string, unknown>;
  assert.equal(logged.level, 'error');
  assert.equal(logged.method, 'GET');

  useMockLists({});
});

test('list endpoints default to 50 rows per page', async () => {
  const mints = makeRows(60, 'mint');
  const transfers = makeRows(60, 'transfer');
  const burns = makeRows(60, 'burn');
  const holders = makeRows(60, 'holder');
  const supplyPoints = makeRows(60, 'point');
  const seenMintsArgs: FindManyArgs[] = [];
  useMockLists({ mints, transfers, burns, holders, supplyPoints, seenMintsArgs });

  await withServer(async (baseUrl) => {
    for (const route of [
      '/api/v1/mints',
      '/api/v1/transfers',
      '/api/v1/burns',
      '/api/v1/holders',
      '/api/v1/supply-history',
    ]) {
      const res = await fetch(`${baseUrl}${route}`, { headers: authHeaders() });
      assert.equal(res.status, 200);
      const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
      assert.equal(body.data.length, 50, `${route} should default to 50 rows`);
      assert.ok(body.nextCursor, `${route} should return a cursor when more rows exist`);
    }

    // Default page fetches limit + 1 rows to detect the next page.
    assert.equal(seenMintsArgs[0]?.take, 51);
    assert.deepEqual(seenMintsArgs[0]?.orderBy, [{ createdAt: 'desc' }, { id: 'desc' }]);
  }, createApiRouter());
});

test('list endpoints never return more than 100 rows', async () => {
  const mints = makeRows(150, 'mint');
  const transfers = makeRows(150, 'transfer');
  const burns = makeRows(150, 'burn');
  const holders = makeRows(150, 'holder');
  const supplyPoints = makeRows(150, 'point');
  useMockLists({ mints, transfers, burns, holders, supplyPoints });

  await withServer(async (baseUrl) => {
    for (const route of [
      '/api/v1/mints',
      '/api/v1/transfers',
      '/api/v1/burns',
      '/api/v1/holders',
      '/api/v1/supply-history',
    ]) {
      const res = await fetch(`${baseUrl}${route}?limit=200`, { headers: authHeaders() });
      assert.equal(res.status, 200);
      const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
      assert.equal(body.data.length, 100, `${route} should cap limit at 100`);
      assert.ok(body.nextCursor, `${route} should page when rows remain`);
    }
  }, createApiRouter());
});

test('non-integer or out-of-range limits return 400', async () => {
  useMockLists({ mints: makeRows(5, 'mint') });

  await withServer(async (baseUrl) => {
    for (const badLimit of ['0', '-5', 'abc', '1.5', 'NaN']) {
      for (const route of [
        '/api/v1/mints',
        '/api/v1/transfers',
        '/api/v1/burns',
        '/api/v1/holders',
        '/api/v1/supply-history',
      ]) {
        const res = await fetch(`${baseUrl}${route}?limit=${encodeURIComponent(badLimit)}`, {
          headers: authHeaders(),
        });
        assert.equal(res.status, 400, `${route}?limit=${badLimit} should be rejected`);
      }
    }
  }, createApiRouter());
});

test('callers can walk every row with nextCursor without gaps or duplicates', async () => {
  // Identical timestamps force the id tie-break to keep pages stable.
  const mints = makeRows(12, 'mint', true);
  useMockLists({ mints });

  await withServer(async (baseUrl) => {
    const collected: Row[] = [];
    let cursor: string | null = null;
    let firstRequest = true;
    let pages = 0;
    do {
      const target =
        firstRequest
          ? `${baseUrl}/api/v1/mints?limit=5`
          : `${baseUrl}/api/v1/mints?limit=5&cursor=${encodeURIComponent(cursor as string)}`;
      firstRequest = false;
      const res = await fetch(target, { headers: authHeaders() });
      assert.equal(res.status, 200);
      const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
      assert.ok(body.data.length <= 5);
      collected.push(...body.data);
      cursor = body.nextCursor;
      pages += 1;
      assert.ok(pages < 10, 'pagination should terminate');
    } while (cursor !== null);

    assert.equal(pages, 3);
    assert.deepEqual(
      collected.map((row) => row.id),
      sortRows(mints).map((row) => row.id),
    );
    assert.equal(new Set(collected.map((row) => row.id)).size, mints.length);
  });
});

test('second page via nextCursor continues where the first page stopped', async () => {
  const transfers = makeRows(8, 'transfer');
  useMockLists({ transfers });

  await withServer(async (baseUrl) => {
    const first = await fetch(`${baseUrl}/api/v1/transfers?limit=3`, {
      headers: authHeaders(),
    });
    assert.equal(first.status, 200);
    const firstBody = (await first.json()) as { data: Row[]; nextCursor: string | null };
    assert.equal(firstBody.data.length, 3);
    assert.ok(firstBody.nextCursor);

    const second = await fetch(
      `${baseUrl}/api/v1/transfers?limit=3&cursor=${encodeURIComponent(firstBody.nextCursor as string)}`,
      { headers: authHeaders() },
    );
    assert.equal(second.status, 200);
    const secondBody = (await second.json()) as { data: Row[]; nextCursor: string | null };
    assert.equal(secondBody.data.length, 3);

    const expected = sortRows(transfers);
    assert.deepEqual(
      [...firstBody.data, ...secondBody.data].map((row) => row.id),
      expected.slice(0, 6).map((row) => row.id),
    );
  });
});

test('address filter returns only matching rows', async () => {
  const target = 'GABC1111';
  const mintRows: Row[] = [
    { id: 'mint-a', to: target, amount: '100', ledger: 10, createdAt: new Date(Date.UTC(2026, 0, 3)) },
    { id: 'mint-b', to: 'GOTHER', amount: '50', ledger: 11, createdAt: new Date(Date.UTC(2026, 0, 2)) },
    { id: 'mint-c', to: target, amount: '200', ledger: 12, createdAt: new Date(Date.UTC(2026, 0, 1)) },
  ];
  const transferRows: Row[] = [
    { id: 'tx-a', from: target, to: 'GOTHER', amount: '10', ledger: 5, createdAt: new Date(Date.UTC(2026, 0, 3)) },
    { id: 'tx-b', from: 'GOTHER', to: target, amount: '20', ledger: 6, createdAt: new Date(Date.UTC(2026, 0, 2)) },
    { id: 'tx-c', from: 'GOTHER', to: 'GOTHER2', amount: '5', ledger: 7, createdAt: new Date(Date.UTC(2026, 0, 1)) },
  ];
  const burnRows: Row[] = [
    { id: 'burn-a', from: target, amount: '30', ledger: 8, createdAt: new Date(Date.UTC(2026, 0, 3)) },
    { id: 'burn-b', from: 'GOTHER', amount: '15', ledger: 9, createdAt: new Date(Date.UTC(2026, 0, 2)) },
  ];
  useMockLists({ mints: mintRows, transfers: transferRows, burns: burnRows });

  await withServer(async (baseUrl) => {
    const mintsRes = await fetch(
      `${baseUrl}/api/v1/mints?address=${encodeURIComponent(target)}`,
      { headers: authHeaders() },
    );
    assert.equal(mintsRes.status, 200);
    const mintsBody = (await mintsRes.json()) as { data: Row[]; nextCursor: string | null };
    assert.ok(
      mintsBody.data.every((r) => r.to === target),
      'all mint rows should match the target address',
    );
    assert.equal(mintsBody.data.length, 2);

    const txRes = await fetch(
      `${baseUrl}/api/v1/transfers?address=${encodeURIComponent(target)}`,
      { headers: authHeaders() },
    );
    assert.equal(txRes.status, 200);
    const txBody = (await txRes.json()) as { data: Row[]; nextCursor: string | null };
    assert.equal(txBody.data.length, 2, 'transfers from OR to the address should be returned');
    assert.ok(txBody.data.every((r) => r.from === target || r.to === target));

    const burnRes = await fetch(
      `${baseUrl}/api/v1/burns?address=${encodeURIComponent(target)}`,
      { headers: authHeaders() },
    );
    assert.equal(burnRes.status, 200);
    const burnBody = (await burnRes.json()) as { data: Row[]; nextCursor: string | null };
    assert.equal(burnBody.data.length, 1);
    assert.equal(burnBody.data[0].from, target);
  });
});

test('from_ledger filter returns only rows at or after the given ledger', async () => {
  const mintRows: Row[] = [
    { id: 'mint-1', to: 'G1', amount: '10', ledger: 5, createdAt: new Date(Date.UTC(2026, 0, 5)) },
    { id: 'mint-2', to: 'G2', amount: '20', ledger: 10, createdAt: new Date(Date.UTC(2026, 0, 4)) },
    { id: 'mint-3', to: 'G3', amount: '30', ledger: 15, createdAt: new Date(Date.UTC(2026, 0, 3)) },
    { id: 'mint-4', to: 'G4', amount: '40', ledger: 20, createdAt: new Date(Date.UTC(2026, 0, 2)) },
  ];
  useMockLists({ mints: mintRows });

  await withServer(async (baseUrl) => {
    const res = await fetch(`${baseUrl}/api/v1/mints?from_ledger=10`, { headers: authHeaders() });
    assert.equal(res.status, 200);
    const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
    assert.equal(body.data.length, 3, 'should include ledger 10, 15, and 20');
    assert.ok(body.data.every((r) => (r.ledger as number) >= 10));
  });
});

test('address filter can be combined with cursor pagination', async () => {
  const target = 'GTARGET';
  const base = Date.UTC(2026, 0, 1);
  const mintRows: Row[] = Array.from({ length: 8 }, (_, i) => ({
    id: `mint-${String(i).padStart(4, '0')}`,
    to: i % 2 === 0 ? target : 'GOTHER',
    amount: '1',
    ledger: i + 1,
    createdAt: new Date(base + i * 1000),
  }));
  useMockLists({ mints: mintRows });

  await withServer(async (baseUrl) => {
    const collected: Row[] = [];
    let cursor: string | null = null;
    let pages = 0;
    do {
      const url = cursor
        ? `${baseUrl}/api/v1/mints?limit=2&address=${target}&cursor=${encodeURIComponent(cursor)}`
        : `${baseUrl}/api/v1/mints?limit=2&address=${target}`;
      const res = await fetch(url, { headers: authHeaders() });
      assert.equal(res.status, 200);
      const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
      collected.push(...body.data);
      cursor = body.nextCursor;
      pages += 1;
      assert.ok(pages < 10, 'pagination must terminate');
    } while (cursor !== null);

    assert.ok(collected.every((r) => r.to === target), 'all rows must match the address filter');
    assert.equal(collected.length, 4, 'should collect exactly 4 target-address rows');
  });
});

test('invalid from_ledger returns 400', async () => {
  useMockLists({});
  await withServer(async (baseUrl) => {
    for (const bad of ['-1', 'abc', '1.5', 'NaN']) {
      for (const route of [
        '/api/v1/mints',
        '/api/v1/transfers',
        '/api/v1/burns',
        '/api/v1/holders',
        '/api/v1/supply-history',
      ]) {
        const res = await fetch(
          `${baseUrl}${route}?from_ledger=${encodeURIComponent(bad)}`,
          { headers: authHeaders() },
        );
        assert.equal(res.status, 400, `${route}?from_ledger=${bad} should be rejected`);
        const body = (await res.json()) as { error: string };
        assert.ok(body.error.includes('from_ledger'));
      }
    }
  }, createApiRouter());
});

test('holders returns one row per current holder with its balance', async () => {
  const holders: Row[] = [
    { id: 'h-1', address: 'GABC', balance: '600', ledger: 12, createdAt: new Date(Date.UTC(2026, 0, 3)) },
    { id: 'h-2', address: 'GDEF', balance: '400', ledger: 11, createdAt: new Date(Date.UTC(2026, 0, 2)) },
  ];
  const seenHoldersArgs: FindManyArgs[] = [];
  useMockLists({ holders, seenHoldersArgs });

  await withServer(async (baseUrl) => {
    const res = await fetch(`${baseUrl}/api/v1/holders`, { headers: authHeaders() });
    assert.equal(res.status, 200);
    const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
    assert.deepEqual(body, {
      data: JSON.parse(JSON.stringify(holders)),
      nextCursor: null,
    });
    assert.deepEqual(seenHoldersArgs[0]?.take, 51);
    assert.equal(body.data[0].address, 'GABC');
    assert.equal(body.data[0].balance, '600');
  }, createApiRouter());
});

test('holders filters by address and combines the filter with pagination', async () => {
  const target = 'GTARGET';
  const holders: Row[] = [
    { id: 'h-1', address: target, balance: '500', ledger: 9, createdAt: new Date(Date.UTC(2026, 0, 3)) },
    { id: 'h-2', address: 'GOTHER', balance: '100', ledger: 8, createdAt: new Date(Date.UTC(2026, 0, 2)) },
    { id: 'h-3', address: target, balance: '250', ledger: 7, createdAt: new Date(Date.UTC(2026, 0, 1)) },
  ];
  const seenHoldersArgs: FindManyArgs[] = [];
  useMockLists({ holders, seenHoldersArgs });

  await withServer(async (baseUrl) => {
    const res = await fetch(
      `${baseUrl}/api/v1/holders?address=${encodeURIComponent(target)}`,
      { headers: authHeaders() },
    );
    assert.equal(res.status, 200);
    const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
    assert.equal(body.data.length, 2);
    assert.ok(body.data.every((r) => r.address === target));
    assert.deepEqual(seenHoldersArgs[0]?.where, { address: target });
  }, createApiRouter());
});

test('holders paginates with nextCursor without gaps or duplicates', async () => {
  const base = Date.UTC(2026, 0, 1);
  const holders = Array.from({ length: 8 }, (_, i) => ({
    id: `h-${String(i).padStart(3, '0')}`,
    address: `G-${String(i).padStart(3, '0')}`,
    balance: `${i}000`,
    createdAt: new Date(base + i * 1000),
  }));
  useMockLists({ holders });

  await withServer(async (baseUrl) => {
    const collected: Row[] = [];
    let cursor: string | null = null;
    let pages = 0;
    do {
      const url = cursor
        ? `${baseUrl}/api/v1/holders?limit=3&cursor=${encodeURIComponent(cursor)}`
        : `${baseUrl}/api/v1/holders?limit=3`;
      const res = await fetch(url, { headers: authHeaders() });
      assert.equal(res.status, 200);
      const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
      collected.push(...body.data);
      cursor = body.nextCursor;
      pages += 1;
      assert.ok(pages < 10, 'pagination should terminate');
    } while (cursor !== null);

    assert.equal(pages, 3);
    assert.deepEqual(
      collected.map((row) => row.id),
      sortRows(holders).map((row) => row.id),
    );
    assert.equal(new Set(collected.map((row) => row.id)).size, holders.length);
  }, createApiRouter());
});

test('supply-history returns timestamped supply points', async () => {
  const supplyPoints: Row[] = [
    { id: 'p-1', timestamp: new Date(Date.UTC(2026, 0, 3)), supply: '1000', ledger: 12, txHash: 't1', createdAt: new Date(Date.UTC(2026, 0, 3)) },
    { id: 'p-2', timestamp: new Date(Date.UTC(2026, 0, 2)), supply: '600', ledger: 11, txHash: 't2', createdAt: new Date(Date.UTC(2026, 0, 2)) },
    { id: 'p-3', timestamp: new Date(Date.UTC(2026, 0, 1)), supply: '400', ledger: 10, txHash: 't3', createdAt: new Date(Date.UTC(2026, 0, 1)) },
  ];
  useMockLists({ supplyPoints });

  await withServer(async (baseUrl) => {
    const res = await fetch(`${baseUrl}/api/v1/supply-history`, { headers: authHeaders() });
    assert.equal(res.status, 200);
    const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
    assert.deepEqual(body, {
      data: JSON.parse(JSON.stringify(supplyPoints)),
      nextCursor: null,
    });
    assert.equal(body.data[0].supply, '1000');
    assert.equal(body.data[0].txHash, 't1');
  }, createApiRouter());
});

test('supply-history filters by from_ledger', async () => {
  const supplyPoints: Row[] = [
    { id: 'p-1', timestamp: new Date(Date.UTC(2026, 0, 3)), supply: '1000', ledger: 15, createdAt: new Date(Date.UTC(2026, 0, 3)) },
    { id: 'p-2', timestamp: new Date(Date.UTC(2026, 0, 2)), supply: '600', ledger: 12, createdAt: new Date(Date.UTC(2026, 0, 2)) },
    { id: 'p-3', timestamp: new Date(Date.UTC(2026, 0, 1)), supply: '400', ledger: 10, createdAt: new Date(Date.UTC(2026, 0, 1)) },
  ];
  const seenSupplyPointsArgs: FindManyArgs[] = [];
  useMockLists({ supplyPoints, seenSupplyPointsArgs });

  await withServer(async (baseUrl) => {
    const res = await fetch(
      `${baseUrl}/api/v1/supply-history?from_ledger=12`,
      { headers: authHeaders() },
    );
    assert.equal(res.status, 200);
    const body = (await res.json()) as { data: Row[]; nextCursor: string | null };
    assert.equal(body.data.length, 2, 'should include ledger 12 and 15');
    assert.ok(body.data.every((r) => (r.ledger as number) >= 12));
    assert.deepEqual(seenSupplyPointsArgs[0]?.where, { ledger: { gte: 12 } });
  }, createApiRouter());
});

// ─── Rate limiting ────────────────────────────────────────────────────────
// These use a fresh `createApiRouter()` per test so each has its own
// in-memory store and is unaffected by the requests the tests above made.

test('the 61st request in the window returns 429 with rate limit headers', async () => {
  useMockLists({});
  await withServer(async (baseUrl) => {
    for (let i = 1; i <= 60; i += 1) {
      const res = await fetch(`${baseUrl}/api/v1/stats`, { headers: authHeaders() });
      assert.equal(res.status, 200, `request ${i} should be under the limit`);
    }

    const limited = await fetch(`${baseUrl}/api/v1/stats`, { headers: authHeaders() });
    assert.equal(limited.status, 429);
    assert.deepEqual(await limited.json(), {
      error: 'Too many requests, please try again later.',
    });
    assert.ok(limited.headers.get('retry-after'), 'Retry-After header should be set');
    assert.ok(limited.headers.get('ratelimit'), 'RateLimit header should be set');
  }, createApiRouter());
});

test('the limit is shared across every /api/v1 route', async () => {
  useMockLists({});
  await withServer(async (baseUrl) => {
    for (let i = 0; i < 30; i += 1) {
      assert.equal(
        (await fetch(`${baseUrl}/api/v1/mints`, { headers: authHeaders() })).status,
        200,
      );
      assert.equal(
        (await fetch(`${baseUrl}/api/v1/transfers`, { headers: authHeaders() })).status,
        200,
      );
    }

    // 60 requests have now been spent, so the next route is limited too.
    assert.equal(
      (await fetch(`${baseUrl}/api/v1/burns`, { headers: authHeaders() })).status,
      429,
    );
  }, createApiRouter());
});

test('GET /health is not counted against the limit', async () => {
  useMockLists({});
  await withServer(async (baseUrl) => {
    for (let i = 0; i < 100; i += 1) {
      assert.equal((await fetch(`${baseUrl}/health`)).status, 200);
    }

    assert.equal(
      (await fetch(`${baseUrl}/api/v1/stats`, { headers: authHeaders() })).status,
      200,
    );
  }, createApiRouter());
});

test('INDEXER_RATE_LIMIT_MAX overrides the default limit', async () => {
  process.env.INDEXER_RATE_LIMIT_MAX = '3';
  try {
    useMockLists({});
    await withServer(async (baseUrl) => {
      for (let i = 1; i <= 3; i += 1) {
        assert.equal(
          (await fetch(`${baseUrl}/api/v1/stats`, { headers: authHeaders() })).status,
          200,
          `request ${i} should be under the configured limit`,
        );
      }

      assert.equal(
        (await fetch(`${baseUrl}/api/v1/stats`, { headers: authHeaders() })).status,
        429,
      );
    }, createApiRouter());
  } finally {
    delete process.env.INDEXER_RATE_LIMIT_MAX;
  }
});

after(() => {
  setPrismaClientFactoryForTests();
  delete process.env.INDEXER_API_TOKEN;
  delete process.env.INDEXER_RATE_LIMIT_MAX;
  delete process.env.INDEXER_RATE_LIMIT_WINDOW_MS;
});
