[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "wasm32v1-none"

[target.wasm32v1-none]
rustflags = ["-C", "target-feature=+simd", "-C", "link-args=-zstack-size=32768"]
