// ─────────────────────────────────────────────────────────────────────────────
// Generated by @bc-forge/codegen — DO NOT EDIT
// Contract: BcForgeToken
// Generated: 2026-05-30T16:16:57.010Z
// ─────────────────────────────────────────────────────────────────────────────


export interface Recipient {
  address: string;
  amount: bigint;
}

export interface LockupInfo {
  amount: bigint;
  unlock_time: bigint;
}

/** Information about an allowance, including amount and expiration. */
export interface AllowanceInfo {
  amount: bigint;
  exp_ledger: number;
}

export interface Proposal {
  approvals: string[];
  creator: string;
  description: string;
  executed: boolean;
}

export type DataKey =
  | { tag: 'Admin' }
  | { tag: 'PendingAdmin' }
  | { tag: 'Allowance'; value0: string; value1: string }
  | { tag: 'Balance'; value0: string }
  | { tag: 'Name' }
  | { tag: 'Symbol' }
  | { tag: 'Decimals' }
  | { tag: 'Supply' }
  | { tag: 'ClawbackAdmin' }
  | { tag: 'Lockup'; value0: string }
  | { tag: 'ProposalAction'; value0: bigint };

/** Possible actions that can be proposed via multi-sig. */
export type TokenAction =
  | { tag: 'Mint'; value0: string; value1: bigint }
  | { tag: 'Pause' }
  | { tag: 'Unpause' };

/** Storage keys for lifecycle state. */
export type LifecycleKey =
  | { tag: 'Paused' };

/** Enumeration of available roles. */
export type Role =
  | { tag: 'Admin' }
  | { tag: 'Minter' };

export type AdminKey =
  | { tag: 'Admin' }
  | { tag: 'Role'; value0: Role; value1: string }
  | { tag: 'AdminPool' }
  | { tag: 'Threshold' }
  | { tag: 'Proposal'; value0: bigint }
  | { tag: 'ProposalIdCounter' };

export enum BcForgeTokenError {
  AlreadyInitialized = 1,
  NotInitialized = 2,
  InvalidAmount = 3,
  InsufficientBalance = 4,
  InsufficientAllowance = 5,
  ContractPaused = 6,
}

export interface BcForgeTokenClient {
  burn(from: string, amount: bigint): Promise<void>;

  mint(to: string, amount: bigint): Promise<{ ok: [] } | { error: TokenError }>;

  name(): Promise<string>;

  pause(): Promise<{ ok: [] } | { error: TokenError }>;

  supply(): Promise<bigint>;

  symbol(): Promise<string>;

  approve(from: string, spender: string, amount: bigint, exp: number): Promise<void>;

  balance(id: string): Promise<bigint>;

  unpause(): Promise<{ ok: [] } | { error: TokenError }>;

  upgrade(new_wasm_hash: Buffer): Promise<{ ok: [] } | { error: TokenError }>;

  version(): Promise<string>;

  clawback(from: string, to: string, amount: bigint): Promise<{ ok: [] } | { error: TokenError }>;

  decimals(): Promise<number>;

  has_role(role: Role, address: string): Promise<boolean>;

  transfer(from: string, to: string, amount: bigint): Promise<void>;

  allowance(from: string, spender: string): Promise<bigint>;

  burn_from(spender: string, from: string, amount: bigint): Promise<void>;

  batch_mint(recipients: Recipient[]): Promise<{ ok: [] } | { error: TokenError }>;

  grant_role(role: Role, address: string): Promise<void>;

  initialize(admin: string, decimal: number, name: string, symbol: string): Promise<{ ok: [] } | { error: TokenError }>;

  lock_tokens(user: string, amount: bigint, unlock_time: bigint): Promise<{ ok: [] } | { error: TokenError }>;

  revoke_role(role: Role, address: string): Promise<void>;

  update_name(new_name: string): Promise<{ ok: [] } | { error: TokenError }>;

  pending_owner(): Promise<string | null>;

  propose_owner(new_admin: string): Promise<{ ok: [] } | { error: TokenError }>;

  transfer_from(spender: string, from: string, to: string, amount: bigint): Promise<void>;

  update_symbol(new_symbol: string): Promise<{ ok: [] } | { error: TokenError }>;

  batch_transfer(from: string, recipients: [string, bigint][]): Promise<void>;

  propose_action(signer: string, action: TokenAction, description: string): Promise<bigint>;

  set_admin_pool(pool: string[], threshold: number): Promise<void>;

  cancel_transfer(): Promise<{ ok: [] } | { error: TokenError }>;

  withdraw_locked(user: string): Promise<void>;

  accept_ownership(): Promise<void>;

  approve_proposal(signer: string, proposal_id: bigint): Promise<void>;

  execute_proposal(proposal_id: bigint): Promise<void>;

  set_clawback_admin(clawback_admin: string): Promise<void>;

  transfer_ownership(new_admin: string): Promise<{ ok: [] } | { error: TokenError }>;
}
